In [2]:
import numpy as np 
import pandas as pd 
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(Y_train)

In [10]:

y_test = encoder.transform(Y_test)

In [11]:
y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0])

In [30]:
# conv to tensor vectors
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [13]:
y_test_tensor.shape

torch.Size([114])

In [14]:
class MySimpleNNN():
    def __init__(self,X):
        self.weights = torch.rand((X.shape[1],1),dtype = torch.float64 , requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64 , requires_grad=True)
    def forward(self , X):
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def Binary_Cross_Entropy(self , y_pred , y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)
        #loss
        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [15]:
learning_rate = 0.1
epochs = 25

In [19]:
model = MySimpleNNN(X_train_tensor)
model.weights

# forward pass
for epoch in range(epochs):
    y_pred = model.forward(X_train_tensor)
    # loss calc
    loss = model.Binary_Cross_Entropy(y_pred , y_train_tensor)
    print(f"{epoch} Loss: {loss}")
    # backward pass 
    loss.backward()
    # parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    #setting the grads to 0
    model.bias.grad.zero_()
    model.weights.grad.zero_()
    #print 
    print(f"Epoch: {epoch+1} , Loss: {loss.item()}")

0 Loss: 4.15585331230292
Epoch: 1 , Loss: 4.15585331230292
1 Loss: 4.048039687924899
Epoch: 2 , Loss: 4.048039687924899
2 Loss: 3.9306055797736468
Epoch: 3 , Loss: 3.9306055797736468
3 Loss: 3.811862282343718
Epoch: 4 , Loss: 3.811862282343718
4 Loss: 3.6930888291651254
Epoch: 5 , Loss: 3.6930888291651254
5 Loss: 3.5689921532290594
Epoch: 6 , Loss: 3.5689921532290594
6 Loss: 3.4389026868882566
Epoch: 7 , Loss: 3.4389026868882566
7 Loss: 3.3035044146464876
Epoch: 8 , Loss: 3.3035044146464876
8 Loss: 3.163078803232972
Epoch: 9 , Loss: 3.163078803232972
9 Loss: 3.015249692392013
Epoch: 10 , Loss: 3.015249692392013
10 Loss: 2.8640162581184248
Epoch: 11 , Loss: 2.8640162581184248
11 Loss: 2.7041145711096504
Epoch: 12 , Loss: 2.7041145711096504
12 Loss: 2.5400962187947447
Epoch: 13 , Loss: 2.5400962187947447
13 Loss: 2.371876498661046
Epoch: 14 , Loss: 2.371876498661046
14 Loss: 2.2086762765436427
Epoch: 15 , Loss: 2.2086762765436427
15 Loss: 2.0484613022257236
Epoch: 16 , Loss: 2.0484613022257236
16 Loss: 1.8924980534648381
Epoch: 17 , Loss: 1.8924980534648381
17 Loss: 1.7454896954651842
Epoch: 18 , Loss: 1.7454896954651842
18 Loss: 1.6087375293219293
Epoch: 19 , Loss: 1.6087375293219293
19 Loss: 1.4796594594412829
Epoch: 20 , Loss: 1.4796594594412829
20 Loss: 1.3632930407115176
Epoch: 21 , Loss: 1.3632930407115176
21 Loss: 1.2541278478058207
Epoch: 22 , Loss: 1.2541278478058207
22 Loss: 1.1606269425242437
Epoch: 23 , Loss: 1.1606269425242437
23 Loss: 1.0828381661483988
Epoch: 24 , Loss: 1.0828381661483988
24 Loss: 1.0200215576301732
Epoch: 25 , Loss: 1.0200215576301732

In [20]:
model.bias

tensor([-0.0769], dtype=torch.float64, requires_grad=True)

In [21]:
model.weights

tensor([[-0.2725],
        [ 0.5029],
        [ 0.3439],
        [ 0.3153],
        [ 0.4451],
        [-0.5038],
        [-0.5418],
        [-0.0094],
        [ 0.4512],
        [-0.0232],
        [ 0.1473],
        [ 0.3051],
        [ 0.3737],
        [ 0.5059],
        [ 0.1195],
        [ 0.1434],
        [-0.2158],
        [-0.1489],
        [ 0.2496],
        [ 0.5412],
        [ 0.1638],
        [ 0.4312],
        [ 0.1495],
        [-0.4494],
        [ 0.0505],
        [-0.5019],
        [ 0.3385],
        [ 0.1572],
        [-0.2269],
        [ 0.1575]], dtype=torch.float64, requires_grad=True)

In [22]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()
print(y_pred) 

accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy : {accuracy.item()}")

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.]])
Accuracy : 0.5263158082962036

In [ ]:
class MySimpleNN2(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [34]:
model = MySimpleNN2(X_train_tensor.shape[1])
loss_function = nn.BCELoss()
optimzer = torch.optim.SGD(model.parameters() , lr = learning_rate)

# forward pass
for epoch in range(epochs):
    y_pred = model(X_train_tensor)
    # loss calc
    loss = loss_function(y_pred , y_train_tensor.view(-1,1))
    print(f"{epoch} Loss: {loss}")
    optimzer.zero_grad()
    # backward pass 
    loss.backward()
    # parameters
    optimzer.step()
    
    #print 
    print(f"Epoch: {epoch+1} , Loss: {loss.item()}")

0 Loss: 1.1029376983642578
Epoch: 1 , Loss: 1.1029376983642578
1 Loss: 0.7233437299728394
Epoch: 2 , Loss: 0.7233437299728394
2 Loss: 0.5207846164703369
Epoch: 3 , Loss: 0.5207846164703369
3 Loss: 0.42034533619880676
Epoch: 4 , Loss: 0.42034533619880676
4 Loss: 0.36258140206336975
Epoch: 5 , Loss: 0.36258140206336975
5 Loss: 0.3246833086013794
Epoch: 6 , Loss: 0.3246833086013794
6 Loss: 0.29756760597229004
Epoch: 7 , Loss: 0.29756760597229004
7 Loss: 0.27698153257369995
Epoch: 8 , Loss: 0.27698153257369995
8 Loss: 0.2606715261936188
Epoch: 9 , Loss: 0.2606715261936188
9 Loss: 0.2473297119140625
Epoch: 10 , Loss: 0.2473297119140625
10 Loss: 0.23614275455474854
Epoch: 11 , Loss: 0.23614275455474854
11 Loss: 0.22657698392868042
Epoch: 12 , Loss: 0.22657698392868042
12 Loss: 0.2182665467262268
Epoch: 13 , Loss: 0.2182665467262268
13 Loss: 0.21095171570777893
Epoch: 14 , Loss: 0.21095171570777893
14 Loss: 0.20444253087043762
Epoch: 15 , Loss: 0.20444253087043762
15 Loss: 0.1985965371131897
Epoch: 16 , Loss: 0.1985965371131897
16 Loss: 0.19330458343029022
Epoch: 17 , Loss: 0.19330458343029022
17 Loss: 0.18848146498203278
Epoch: 18 , Loss: 0.18848146498203278
18 Loss: 0.18405957520008087
Epoch: 19 , Loss: 0.18405957520008087
19 Loss: 0.17998456954956055
Epoch: 20 , Loss: 0.17998456954956055
20 Loss: 0.1762121170759201
Epoch: 21 , Loss: 0.1762121170759201
21 Loss: 0.17270562052726746
Epoch: 22 , Loss: 0.17270562052726746
22 Loss: 0.16943462193012238
Epoch: 23 , Loss: 0.16943462193012238
23 Loss: 0.16637355089187622
Epoch: 24 , Loss: 0.16637355089187622
24 Loss: 0.1635006219148636
Epoch: 25 , Loss: 0.1635006219148636

## OPTIM

variety of optimisation algo used to update the params of one model in training 
SGD , ADAM , RMSprop etc etc
It is an iterator can do most of the things